apiVersion: v1
kind: Secret
metadata:
  name: neuralk-secrets
  namespace: neuralk
type: Opaque
stringData:
  MINIO_ROOT_USER: "minioadmin"
  MINIO_ROOT_PASSWORD: "minioadmin"
  # REDIS_PASSWORD: "your-redis-password"
