global:
  # Align Prometheus scrape interval with the OTel SDKs' export interval for consistency (see OTEL_METRIC_EXPORT_INTERVAL)
  scrape_interval: 60s

scrape_configs:
  - job_name: 'opentelemetry-collector'
    static_configs:
      - targets: ['opentelemetry-collector:8889']
    scrape_interval: 10s
    metrics_path: /metrics