apiVersion: v1
kind: Secret
metadata:
  name: {{ include "neuralk.fullname" . }}-secrets
  namespace: {{ .Values.namespace.name | default (printf "neuralk-%s" .Values.global.environment) }}
  labels:
    {{- include "neuralk.labels" . | nindent 4 }}
type: Opaque
stringData:
  MINIO_ROOT_USER: {{ .Values.minio.credentials.accessKey }}
  MINIO_ROOT_PASSWORD: {{ .Values.minio.credentials.secretKey }}
  # Redis password if defined
  {{- if .Values.redis.password }}
  REDIS_PASSWORD: {{ .Values.redis.password }}
  {{- end }}
