{{- if .Values.server.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "neuralk.fullname" . }}-server
  namespace: {{ .Values.namespace.name | default (printf "neuralk-%s" .Values.global.environment) }}
  labels:
    {{- include "neuralk.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  replicas: {{ .Values.server.replicaCount }}
  selector:
    matchLabels:
      {{- include "neuralk.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: server
  template:
    metadata:
      labels:
        {{- include "neuralk.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: server
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: server
          image: {{ include "neuralk.server.image" . }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "neuralk.fullname" . }}-config
            {{- if .Values.redis.password }}
            - secretRef:
                name: {{ include "neuralk.fullname" . }}-secrets
            {{- end }}
          resources:
            {{- toYaml .Values.server.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "neuralk.fullname" . }}-server
  namespace: {{ .Values.namespace.name | default (printf "neuralk-%s" .Values.global.environment) }}
  labels:
    {{- include "neuralk.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "neuralk.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: server
{{- end }}
